tasks:
  - name: frontend
    before: |
      cd ./frontend/
    init: |
      npm install
      npm run build
    command: |
      npm run start

  - name: backend
    before: |
      cd ./backend/
    init: |
      npm install
    command: |
      npm run start:dev